[[headers]]
  for = "**/*.png"
  [headers.values]
    Cache-Control = "public, max-age=5184000, s-maxage=5184000"

[[headers]]
  for = "**/*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=5184000, s-maxage=5184000"